// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uenngqvjhyhvnxrxwqex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbm5ncXZqaHlodm54cnh3cWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTgxOTAsImV4cCI6MjA2Nzc5NDE5MH0.eLUGpp4ryXsx3i_m1jXHYBBL6spcPr-J8yjPAbADs_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});